create table if not exists public.community_daily_checkins (
  user_id uuid not null references auth.users(id) on delete cascade,
  checkin_date date not null,
  points_awarded integer not null default 1 check (points_awarded = 1),
  created_at timestamptz not null default now(),
  primary key (user_id, checkin_date)
);

create table if not exists public.community_point_ledger (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  amount integer not null check (amount <> 0 and amount between -100000 and 100000),
  reason text not null check (reason in ('daily_checkin', 'post_like', 'admin_adjustment')),
  source_key text not null check (char_length(source_key) between 1 and 240),
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  unique (reason, source_key)
);

create index if not exists community_point_ledger_user_created_idx
  on public.community_point_ledger (user_id, created_at desc);

alter table public.community_daily_checkins enable row level security;
alter table public.community_point_ledger enable row level security;

drop policy if exists "Users can read own community checkins" on public.community_daily_checkins;
create policy "Users can read own community checkins"
  on public.community_daily_checkins
  for select
  to authenticated
  using ((select auth.uid()) = user_id);

drop policy if exists "Users can read own community points" on public.community_point_ledger;
create policy "Users can read own community points"
  on public.community_point_ledger
  for select
  to authenticated
  using ((select auth.uid()) = user_id);

grant select on public.community_daily_checkins to authenticated;
grant select on public.community_point_ledger to authenticated;
grant select, insert, update, delete on public.community_daily_checkins to service_role;
grant select, insert, update, delete on public.community_point_ledger to service_role;
grant usage, select on sequence public.community_point_ledger_id_seq to service_role;
revoke insert, update, delete on public.community_daily_checkins from anon, authenticated;
revoke insert, update, delete on public.community_point_ledger from anon, authenticated;

create or replace function public.get_community_point_status(
  p_user_id uuid,
  p_checkin_date date
)
returns table (
  checked_today boolean,
  total_points bigint,
  streak integer,
  checkin_date date
)
language sql
security invoker
set search_path = public
as $$
  with ordered_checkins as (
    select
      daily.checkin_date,
      row_number() over (order by daily.checkin_date desc) as row_number
    from public.community_daily_checkins daily
    where daily.user_id = p_user_id
      and daily.checkin_date <= p_checkin_date
  ),
  streak_summary as (
    select count(*)::integer as streak
    from ordered_checkins
    where checkin_date = p_checkin_date - ((row_number - 1)::integer)
  )
  select
    exists (
      select 1
      from public.community_daily_checkins daily
      where daily.user_id = p_user_id
        and daily.checkin_date = p_checkin_date
    ) as checked_today,
    coalesce((
      select sum(ledger.amount)
      from public.community_point_ledger ledger
      where ledger.user_id = p_user_id
    ), 0)::bigint as total_points,
    coalesce((select streak from streak_summary), 0)::integer as streak,
    p_checkin_date as checkin_date;
$$;

create or replace function public.record_community_daily_checkin(
  p_user_id uuid,
  p_checkin_date date
)
returns table (
  checked_today boolean,
  total_points bigint,
  streak integer,
  checkin_date date,
  awarded boolean
)
language plpgsql
security invoker
set search_path = public
as $$
declare
  inserted_count integer := 0;
begin
  insert into public.community_daily_checkins (user_id, checkin_date)
  values (p_user_id, p_checkin_date)
  on conflict (user_id, checkin_date) do nothing;

  get diagnostics inserted_count = row_count;

  if inserted_count = 1 then
    insert into public.community_point_ledger (user_id, amount, reason, source_key, metadata)
    values (
      p_user_id,
      1,
      'daily_checkin',
      p_user_id::text || ':' || p_checkin_date::text,
      jsonb_build_object('checkin_date', p_checkin_date)
    )
    on conflict (reason, source_key) do nothing;
  end if;

  return query
  select
    status.checked_today,
    status.total_points,
    status.streak,
    status.checkin_date,
    inserted_count = 1
  from public.get_community_point_status(p_user_id, p_checkin_date) status;
end;
$$;

create or replace function public.award_community_post_like_point(
  p_recipient_user_id uuid,
  p_liker_user_id uuid,
  p_post_id text
)
returns boolean
language plpgsql
security invoker
set search_path = public
as $$
declare
  inserted_count integer := 0;
begin
  if p_recipient_user_id is null
    or p_liker_user_id is null
    or p_recipient_user_id = p_liker_user_id
    or nullif(trim(p_post_id), '') is null then
    return false;
  end if;

  insert into public.community_point_ledger (user_id, amount, reason, source_key, metadata)
  values (
    p_recipient_user_id,
    1,
    'post_like',
    'post:' || p_post_id || ':liker:' || p_liker_user_id::text,
    jsonb_build_object('post_id', p_post_id, 'liker_user_id', p_liker_user_id)
  )
  on conflict (reason, source_key) do nothing;

  get diagnostics inserted_count = row_count;
  return inserted_count = 1;
end;
$$;

revoke all on function public.get_community_point_status(uuid, date) from public, anon, authenticated;
revoke all on function public.record_community_daily_checkin(uuid, date) from public, anon, authenticated;
revoke all on function public.award_community_post_like_point(uuid, uuid, text) from public, anon, authenticated;

grant execute on function public.get_community_point_status(uuid, date) to service_role;
grant execute on function public.record_community_daily_checkin(uuid, date) to service_role;
grant execute on function public.award_community_post_like_point(uuid, uuid, text) to service_role;
